name: Update Changelog

on:
  push:
    tags:
      - 'v*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git identity (local only)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: npm ci

      - name: Update changelog (skip version bump and tag)
        run: npm run release

      - name: Push changelog update if any
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add CHANGELOG.md package.json
            git commit -m "docs: update changelog after release"
            git push origin HEAD:main
          else
            echo "No changes to push"
          fi
