name: Generate Changelog on Release

on:
  create:
    tags:
      - 'v*.*.*'   

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'    

      - name: Install dependencies
        run: npm ci

      - name: Generate changelog and bump version
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes and tags
        run: |
          git push origin HEAD --follow-tags
