version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day : "monday"
      time : "00:00"
      timezone: "Europe/Athens"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    rebase-strategy: "auto"
    target-branch: "chore/dependencies/npm"
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day : "monday"
      time : "01:00"
      timezone: "Europe/Athens"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
    rebase-strategy: "auto"
    target-branch: "chore/dependencies/github-actions"