name: Lint Code (ESLint + Prettier)

on:
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint auto-fix
        run: npx eslint . --fix

      - name: Run Prettier auto-fix
        run: npx prettier . --write

      - name: Check ESLint again (fail if issues remain)
        run: npx eslint .

      - name: Check Prettier formatting
        run: npx prettier . --check
